<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-05T18:16:21 IST" name="Default suite" finished-at="2023-07-05T18:16:23 IST" duration-ms="2108">
    <groups>
    </groups>
    <test started-at="2023-07-05T18:16:21 IST" name="Default test" finished-at="2023-07-05T18:16:23 IST" duration-ms="2108">
      <class name="Basic_Concepts.ExpectedException_12">
        <test-method signature="name()[pri:0, instance:Basic_Concepts.ExpectedException_12@2b662a77]" started-at="2023-07-05T18:16:21 IST" name="name" finished-at="2023-07-05T18:16:23 IST" duration-ms="2036" status="PASS">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method Basic_Concepts.ExpectedException_12.name() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Basic_Concepts.ExpectedException_12.name() didn't finish within the time-out 2000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:465)
at Basic_Concepts.ExpectedException_12.name(ExpectedException_12.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- name -->
      </class> <!-- Basic_Concepts.ExpectedException_12 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
